# Generated by Django 5.2.7 on 2025-11-17 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staff_student_remove_user_staff_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('ADMIN', 'Administration'), ('ACCOUNTS', 'Accounts'), ('LIBRARY', 'Library'), ('OTHER', 'Other')], help_text='Department for which this staff is the HOD', max_length=50)),
                ('start_date', models.DateField(help_text='Date when the staff member became HOD of this department')),
                ('end_date', models.DateField(blank=True, help_text='Date when the staff member stopped being HOD (if applicable)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this HOD assignment is currently active')),
                ('additional_responsibilities', models.TextField(blank=True, help_text='Any additional responsibilities or notes for this HOD role', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.OneToOneField(help_text='Staff member who is the Head of Department', on_delete=django.db.models.deletion.CASCADE, related_name='hod_role', to='users.staff')),
            ],
            options={
                'verbose_name': 'Head of Department',
                'verbose_name_plural': 'Heads of Department',
                'db_table': 'head_of_department',
                'ordering': ['department', '-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department', 'is_active'), name='unique_active_hod_per_department')],
            },
        ),
    ]
