# Generated by Django 5.2.7 on 2025-11-15 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Staff Meeting', 'Staff Meeting'), ('Invigilation Duty', 'Invigilation Duty'), ('Internal Circular', 'Internal Circular'), ('Timetable Work', 'Timetable Work'), ('Leave / Policy Update', 'Leave / Policy Update'), ('Faculty Training', 'Faculty Training'), ('Research Opportunities', 'Research Opportunities'), ('Staff Achievements', 'Staff Achievements'), ('Maintenance Notices', 'Maintenance Notices'), ('IT & System Updates', 'IT & System Updates'), ('Holiday Announcement', 'Holiday Announcement'), ('Exam Timetable', 'Exam Timetable'), ('Events', 'Events'), ('Results', 'Results'), ('Fee Notices', 'Fee Notices'), ('Emergency Alerts', 'Emergency Alerts'), ('Workshops / Seminars', 'Workshops / Seminars'), ('Scholarship / Grants', 'Scholarship / Grants'), ('Campus News', 'Campus News'), ('Sports / Cultural Updates', 'Sports / Cultural Updates')], max_length=50)),
                ('audience', models.CharField(choices=[('staff', 'Staff Only'), ('all', 'All Users')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
