# Generated by Django 5.2.7 on 2025-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=1, help_text='Unique code for the subject (e.g., CS101, MAT201)', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
