# Generated by Django 5.2.7 on 2025-11-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_subject_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['department', 'semester', 'name']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EE', 'Electrical & Electronics Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('IT', 'Information Technology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(editable=False, help_text='Auto-generated code in format: {dept}{semester}{number} (e.g., CSE1101)', max_length=10, unique=True),
        ),
    ]
